name = "Chrono Trigger Jets of Time"
home = "https://discord.com/channels/731205301247803413/1063559984148906035"

[versions]
"0.0.1" = { url = "https://multiworld.ctjot.com/static/multiworld/ctjot.apworld" }
