name = "EarthBound"
home = "https://discord.com/channels/731205301247803413/1077266688657068032"

[versions]
"1.3.0" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthbound1.3/earthbound.apworld" }
