name = "Manual: Pokemon Snap (N64) - Wonderful"
home = "https://discord.com/channels/1097532591650910289/1231737689951178773"

[versions]
"1.2.1" = { local = "../apworlds/manual_pokemonsnapwndrfl_alirobotnik-1.2.1.apworld" }
