name = "Manual: Rhythm Doctor"
home = "https://discord.com/channels/731205301247803413/1240437664692572312"

[versions]
"0.0.1" = { local = "../apworlds/manual_rhythmdoctor_crimsondestroyer-0.0.1.apworld" }
