name  = "Hatsune Miku Project Diva Mega Mix+"
home = "https://discord.com/channels/731205301247803413/1241134454391443580"
default_url = "https://github.com/Cynichill/DivaAPworld/releases/download/{{version}}/megamix.apworld"

[versions]
# 1.0.3 BETA with https://github.com/Cynichill/DivaAPworld/pull/2 applied
"1.0.3-beta" = { local = "../apworlds/megamix-1.0.3-beta.patched.apworld" }
