name = "Metroid Prime"
home = "https://discord.com/channels/731205301247803413/1172631093837570068"
# XXX: When updating, rezip with the LICENSE

[versions]
"0.2.12" = { local = "../apworlds/metroidprime-0.2.12.apworld" }
