name = "Mario Kart 64"
home = "https://discord.com/channels/731205301247803413/1124649084544876615"
disabled = true

[versions]
"0.2.1-c" = { url = "https://github.com/Edsploration/MK64-Archipelago/releases/download/mk64%2F0.2.1c/mk64.apworld" }
