name = "osu!"
home = "https://discord.com/channels/731205301247803413/1195040661171355730"

[versions]
# This is a patched version containing https://github.com/lilymnky-F/Archipelago-Osu/pull/11
"1.0.2-beta+faststartup" = { local = "../apworlds/osu-1.0.2+faststartup.apworld" }
