on: [push]

name: CI

jobs:
  deploy:
    environment: production
    name: Deploy
    runs-on: ubuntu-latest
    if:
      contains('
        refs/heads/main
      ', github.ref)
    steps:
      - name: Setup ssh
        run: |
          mkdir .ssh
          chmod 700 .ssh
          echo "${{ secrets.DEPLOY_KEY }}" > .ssh/id_ed25519
          wc .ssh/id_ed25519
          wc -l .ssh/id_ed25519
          sha1sum .ssh/id_ed25519
          chmod 600 .ssh/id_ed25519
      - name: Update index
        run: ssh -o StrictHostKeyChecking=no -i .ssh/id_ed25519 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOSTNAME }} "cd ${{ secrets.DEPLOY_PATH }} && git pull && touch ../apwm"
